jenkins:
  # numExecutors: 1
  # mode: NORMAL
  scmCheckoutRetryCount: 5
  # labelString: "master-label"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: admin
          password: ${adminpw:-admin} # the '-' is ignored

  authorizationStrategy:
    globalMatrix:
      grantedPermissions:
        - "Overall/Administer:admin"
        - "Overall/Read:anonymous"
        - "View/Read:anonymous"
        - "Job/Read:anonymous"
        - "Job/Build:anonymous"
        - "Job/Cancel:authenticated"

  globalNodeProperties:
    - envVars:
        env:
        - key: "SOME_KEY"
          value: "SOME_VALUE"
  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true

# https://github.com/jenkinsci/configuration-as-code-plugin/blob/466163288f86adc13415a1287525141a44e3b87e/docs/seed-jobs.md
jobs:
  - file: "/data/jenkins/seed_job.groovy"

tool:
  git:
    installations:
    - home: "/usr/bin/git"
      name: "Default"

security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
